name: Continuous Integration
on: [push]

env:
  PERSONAL_BRANCH_PREFIX: refs/heads/personal/

jobs:
  build:
    name: Gated Build
    runs-on: ubuntu-18.04
    steps:
      - name: Dump variables
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "env.PERSONAL_BRANCH_PREFIX = ${{ env.PERSONAL_BRANCH_PREFIX }}"

      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Catch up from master
        if: startsWith(github.ref, env.PERSONAL_BRANCH_PREFIX)
        run: |
          git fetch --prune origin master
          git merge origin/master

      - name: Run normal CI steps
        run: |
          echo "Build the code, run the tests, etc"

      - name: Promote changes to master
        if: startsWith(github.ref, env.PERSONAL_BRANCH_PREFIX)
        run: |
          git checkout master
          git merge ${{ github.ref }}
          git push --set-upstream origin master
