name: Continuous Integration
on:
  push:
  repository_dispatch:
    types: [trigger-workflow-ci]

env:
  PERSONAL_BRANCH_PREFIX: refs/heads/personal/

jobs:
  build:
    name: Gated Build
    runs-on: ubuntu-18.04
    steps:
      - name: Check out (triggered workflow)
        if: github.event_name == 'repository_dispatch'
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master

      - name: Check out (normal workflow)
        if: github.event_name != 'repository_dispatch'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Catch up
        if: startsWith(github.ref, env.PERSONAL_BRANCH_PREFIX)
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github.actions@example.com"

          git fetch --prune origin master
          git merge origin/master

      - name: Run normal CI steps
        run: |
          echo "Build the code, run the tests, etc"

      - name: Promote
        if: startsWith(github.ref, env.PERSONAL_BRANCH_PREFIX)
        run: |
          git push
          git checkout master
          git merge ${{ github.ref }}
          git push --set-upstream origin master

      - name: Trigger build on master
        if: startsWith(github.ref, env.PERSONAL_BRANCH_PREFIX)
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_ACCESS_TOKEN }}
          event-type: blah
